name: Check SonarCloud Status

on:
  issue_comment:
    types: [created]

jobs:
  sonarcloud_report:
    name: SonarCloud Report
    if: ${{ github.event.sender.login == 'sonarcloud[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo A comment on sender $SENDER
        env:
          SENDER: ${{ github.event.comment.body }}
      - name: Trigger Action
        uses: octokit/request-action@v2.x
        id: create_check_run
        with:
          route: POST /repos/{owner}/{repo}/check-runs
          owner: ${{ github.event.repository.owner.login }}
          repo: ${{ github.event.repository.name }}
          name: "SonarCloud Report"
          head_sha: ${{ github.sha }}
          output: | # The | is significant!
            title: SonarCloud Report
            summary: A summary of the test check run
            images:
              - alt: Test image
                image_url: https://octodex.github.com/images/jetpacktocat.png
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # Update check run to completed, successful status
      - name: Update Successful Action
        uses: octokit/request-action@v2.x
        id: update_check_run_success
        with:
          route: PATCH /repos/{owner}/{repo}/check-runs/{check_run_id}
          owner: ${{ github.event.repository.owner.login }}
          repo: ${{ github.event.repository.name }}
          check_run_id: ${{ fromJson(steps.create_check_run.outputs.data).id }}
          conclusion: "success"
          status: "completed"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Update Failed Action
        uses: octokit/request-action@v2.x
        id: update_check_run_failed
        with:
          route: PATCH /repos/{owner}/{repo}/check-runs/{check_run_id}
          owner: ${{ github.event.repository.owner.login }}
          repo: ${{ github.event.repository.name }}
          check_run_id: ${{ fromJson(steps.create_check_run.outputs.data).id }}
          conclusion: "failure"
          status: "completed"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
