# Controls when the workflow will run
on:
  # Trigger analysis when pushing in master or pull requests, and when creating
  # a pull request.
  push:
    branches:
      - master
  pull_request:
      types: [opened, synchronize, reopened]

name: CI
jobs:
  pre_job:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
      paths_result: ${{ steps.skip_check.outputs.paths_result }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@master
        with:
          paths_filter: |
            client:
              paths_ignore:
                - 'client/docs/**/*'
              paths:
                - 'client/**/*'
              backtracking: 10
            server:
              paths:
                - 'server/**/*'
              backtracking: 10
  client:
    needs: pre_job
    if: ${{ !fromJSON(needs.pre_job.outputs.paths_result).client.should_skip }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      with:
        projectBaseDir: client
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  server:
    needs: pre_job
    if: ${{ !fromJSON(needs.pre_job.outputs.paths_result).server.should_skip }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      with:
        projectBaseDir: server
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  skipped-sonarcloud-result-client:
    name: SonarCloud Result Client
    uses: hakiemaul/hacktivpress/.github/workflows/reusable-sonarcloud-result-skipped.yml@master
    with:
      filters: |
        changed:
          - client/**

  skipped-sonarcloud-result-server:
    name: SonarCloud Result Server
    uses: hakiemaul/hacktivpress/.github/workflows/reusable-sonarcloud-result-skipped.yml@master
    with:
      filters: |
        changed:
          - server/**
