# Controls when the workflow will run
on:
  # Trigger analysis when pushing in master or pull requests, and when creating
  # a pull request.
  push:
    branches:
      - master
  pull_request:
      types: [opened, synchronize, reopened]

name: CI
jobs:
  clients:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        initial-fetch-depth: 10
        filters: |
          changed:
            - clients/**
    - name: SonarCloud Scan
      if: ${{ steps.filter.outputs.changed == 'true' }}
      uses: sonarsource/sonarcloud-github-action@master
      with:
        projectBaseDir: client
        args: >
          -Dsonar.branch.name=${GIT_BRANCH}
          -Dsonar.projectName=clients
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  server:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        initial-fetch-depth: 10
        filters: |
          changed:
            - servers/**
    - name: SonarCloud Scan
      if: ${{ steps.filter.outputs.changed == 'true' }}
      uses: sonarsource/sonarcloud-github-action@master
      with:
        projectBaseDir: servers
        args: >
          -Dsonar.branch.name=${GIT_BRANCH}
          -Dsonar.projectName=servers
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  skipped-sonarcloud-result-client:
    name: SonarCloud Result Client
    uses: hakiemaul/hacktivpress/.github/workflows/reusable-sonarcloud-result-skipped.yml@client
    with:
      filters: |
        changed:
          - clients/**

  skipped-sonarcloud-result-server:
    name: SonarCloud Result Server
    uses: hakiemaul/hacktivpress/.github/workflows/reusable-sonarcloud-result-skipped.yml@client
    with:
      filters: |
        changed:
          - servers/**
